graph TD
    A(("Начало"))
    B[/"Ввод: f, x0, y0, n, h"/]
    C["result = []\n x = x0\n y=y0"]
    D["Добавить (x, y) в result"]
    E{{"i=1, i < n"}}
    F["y += h * f(x, y)"]
    H["x += h"]
    I["Добавить (x, y) в result"]
    J[/"Возврат result"/]
    K(("Конец"))

    A --> B --> C --> D --> E
    E -- true --> F --> H --> I --> E
    E -- false --> J --> K
