graph TD
    A(("Начало"))
    B[/"Ввод: f, x0, y0, n, h"/]
    C["result = []\n x = x0\n y=y0"]
    D["Добавить (x, y) в result"]
    E{{"1 <= i <= n"}}
    F["k_1 = h * f(x, y) \n k_2 = h * f(x + h/2, y + k_1/2) \n k_3 = h * f(x + h/2, y + k_2/2) \n k_4 = h * f(x + h, y + k_3) "]
    G["y += (k_1 + 2k_2 + 2k_3 + k_4) / 6"]
    H["x += h"]
    I["Добавить (x, y) в result"]
    J[/"Возврат result"/]
    K(("Конец"))

    A --> B --> C --> D --> E
    E -- true --> F --> G --> H --> I --> E
    E -- false --> J --> K
